### ISSUE TITLE
功能支持

### ISSUE THREAD

**Issue by xaioxw** [AshenvaleZX/ZXEngine#1]
可以提供对 macos  平台的支持吗，编译是使用cmakelist

**Comment by AshenvaleZX** [comment]
我公司的开发环境以及我个人的电脑都是Windows，我本人对Mac OS也不熟，所以只做了Windows平台的支持。
这个项目是我用空余时间做着玩的，还有挺多想法没实现，但是时间和精力有限所以难免会有不周全的地方。本项目我会长期更新下去，跨平台的支持也想过，但是优先级比较低，我现在也没有Mac的环境，因此短期内不会排上开发日程表。
所以不好意思了啊，暂时还没有提供支持。

**Comment by xaioxw** [comment]
您的邮件我已收到，我会尽快恢复的

**Comment by xaioxw** [comment]
编译工具可以支持使用cmake 吗

**Comment by AshenvaleZX** [comment]
CMake近期可以考虑，过几天空了搞，我尽量在后两周内加上CMake吧

**Comment by AshenvaleZX** [comment]
已添加CMakeList，不过暂时还是只支持Windows下的构建：)

**Comment by AshenvaleZX** [comment]
> 可以提供对 macos 平台的支持吗，编译是使用cmakelist

目前已经支持MacOS了哦，使用的xmake作为构建工具。

**Comment by xaioxw** [comment]
您的邮件我已收到，我会尽快恢复的
